/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module traffic_controller(clk, reset, enable, red, green, yellow);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  input clk;
  wire clk;
  input enable;
  wire enable;
  output green;
  wire green;
  output red;
  wire red;
  input reset;
  wire reset;
  wire [1:0] state;
  wire [27:0] timer;
  output yellow;
  wire yellow;
  sky130_fd_sc_hd__clkinv_1 _07_ (
    .A(state[0]),
    .Y(_05_)
  );
  sky130_fd_sc_hd__nand2b_1 _08_ (
    .A_N(state[1]),
    .B(enable),
    .Y(_06_)
  );
  sky130_fd_sc_hd__a21oi_1 _09_ (
    .A1(_05_),
    .A2(_06_),
    .B1(reset),
    .Y(_00_)
  );
  sky130_fd_sc_hd__lpflow_isobufsrc_1 _10_ (
    .A(state[1]),
    .SLEEP(reset),
    .X(_01_)
  );
  sky130_fd_sc_hd__and2_0 _11_ (
    .A(_05_),
    .B(_01_),
    .X(_02_)
  );
  sky130_fd_sc_hd__and2_0 _12_ (
    .A(state[0]),
    .B(_01_),
    .X(_03_)
  );
  sky130_fd_sc_hd__a211oi_1 _13_ (
    .A1(_05_),
    .A2(_06_),
    .B1(state[1]),
    .C1(reset),
    .Y(_04_)
  );
  sky130_fd_sc_hd__dfxtp_1 _14_ (
    .CLK(clk),
    .D(_00_),
    .Q(state[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _15_ (
    .CLK(clk),
    .D(_01_),
    .Q(state[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _16_ (
    .CLK(clk),
    .D(_02_),
    .Q(green)
  );
  sky130_fd_sc_hd__dfxtp_1 _17_ (
    .CLK(clk),
    .D(_03_),
    .Q(yellow)
  );
  sky130_fd_sc_hd__dfxtp_1 _18_ (
    .CLK(clk),
    .D(_04_),
    .Q(red)
  );
  assign timer = 28'b000xx1xx1x0xx1xxx0xxxx000000;
endmodule
