# day4_strings.py - String Operations

import re

# ============================================
# BASIC STRING OPERATIONS
# ============================================

print("=" * 50)
print("BASIC STRING OPERATIONS")
print("=" * 50)

description = "  Create an 8-bit ADDER with carry  "

clean = description.strip()
print(f"Original: '{description}'")
print(f"Stripped: '{clean}'")
print(f"Lowercase: {description.lower()}")
print(f"Uppercase: {description.upper()}")
print(f"Title case: {description.title()}")
print(f"Contains 'adder'? {'adder' in description.lower()}")
print(f"Starts with 'Create'? {clean.startswith('Create')}")
print(f"Ends with 'carry'? {clean.endswith('carry')}")

# ============================================
# SEARCHING AND REPLACING
# ============================================

print("\n" + "=" * 50)
print("SEARCH AND REPLACE")
print("=" * 50)

text = "Create an 8-bit adder and an 8-bit counter"

pos = text.find('8-bit')
print(f"'8-bit' found at position: {pos}")

new_text = text.replace('8-bit', '16-bit')
print(f"Original: {text}")
print(f"Replaced: {new_text}")

first_only = text.replace('8-bit', '16-bit', 1)
print(f"First only: {first_only}")

count_8bit = text.count('8-bit')
print(f"'8-bit' appears {count_8bit} times")

# ============================================
# SPLITTING AND JOINING
# ============================================

print("\n" + "=" * 50)
print("SPLIT AND JOIN")
print("=" * 50)

words = clean.split()
print(f"Words: {words}")

ports = "clk, rst, data_in, data_out"
port_list = ports.split(', ')
print(f"Ports: {port_list}")

joined = ' | '.join(port_list)
print(f"Joined with ' | ': {joined}")

# ============================================
# EXTRACTING INFORMATION
# ============================================

print("\n" + "=" * 50)
print("EXTRACTING INFORMATION")
print("=" * 50)


def extract_bit_width(text):
    """Extract bit width from description"""
    text = text.lower()
    for width in [64, 32, 16, 8, 4]:
        if f"{width}-bit" in text or f"{width} bit" in text:
            return width
    words = text.split()
    for i, word in enumerate(words):
        if 'bit' in word and i > 0 and words[i - 1].isdigit():
            return int(words[i - 1])
    return None


test_strings = [
    "Create an 8-bit adder",
    "16-bit counter with enable",
    "Design a 32 bit ALU",
    "Build a 4bit register"
]

for s in test_strings:
    width = extract_bit_width(s)
    print(f"'{s}' -> {width} bits")

# ============================================
# F-STRING FORMATTING
# ============================================

print("\n" + "=" * 50)
print("F-STRING FORMATTING")
print("=" * 50)

component = "adder"
bit_width = 8

print(f"Creating {bit_width}-bit {component}")
print(f"Bit width in hex: {bit_width:x}")
print(f"Bit width in binary: {bit_width:b}")

pi = 3.14159265359
print(f"Pi to 2 decimals: {pi:.2f}")
print(f"Pi to 4 decimals: {pi:.4f}")

name = "adder"
print(f"|{name:<10}|")
print(f"|{name:^10}|")
print(f"|{name:>10}|")

module_template = f"""
module {component}_{bit_width}bit(
    input [{bit_width-1}:0] a,
    input [{bit_width-1}:0] b,
    output [{bit_width-1}:0] sum,
    output carry
);
    assign {{carry, sum}} = a + b;
endmodule
"""
print(module_template)

# ============================================
# CLEANING LLM OUTPUT
# ============================================

print("\n" + "=" * 50)
print("CLEANING LLM OUTPUT")
print("=" * 50)


def extract_code_from_markdown(text):
    """Extract code from markdown code blocks"""
    lines = text.split('\n')
    in_code_block = False
    code_lines = []
    language = None

    for line in lines:
        if line.startswith('```'):
            if not in_code_block:
                language = line[3:].strip() or "unknown"
                in_code_block = True
            else:
                in_code_block = False
        elif in_code_block:
            code_lines.append(line)

    return '\n'.join(code_lines), language


llm_output = """Here's the Verilog code for an 8-bit adder:

```verilog
module adder_8bit(
    input [7:0] a,
    input [7:0] b,
    output [7:0] sum,
    output carry
);
    assign {carry, sum} = a + b;
endmodule
```

This implements a simple adder circuit.
"""

code, lang = extract_code_from_markdown(llm_output)
print(f"Extracted {lang} code:")
print(code)

# ============================================
# BUILDING VERILOG CODE WITH STRINGS
# ============================================

print("\n" + "=" * 50)
print("BUILDING VERILOG CODE")
print("=" * 50)


def build_verilog_module(module_name, inputs, outputs):
    """Build Verilog module from specifications"""
    lines = []
    lines.append(f"// {module_name}.v")
    lines.append("// Generated by RTL-Gen AII")
    lines.append("")
    lines.append(f"module {module_name}(")

    port_lines = []
    for n, width in inputs:
        if width > 1:
            port_lines.append(f"    input [{width-1}:0] {n}")
        else:
            port_lines.append(f"    input {n}")

    for n, width in outputs:
        if width > 1:
            port_lines.append(f"    output [{width-1}:0] {n}")
        else:
            port_lines.append(f"    output {n}")

    for i, line in enumerate(port_lines):
        if i < len(port_lines) - 1:
            lines.append(line + ",")
        else:
            lines.append(line)

    lines.append(");")
    lines.append("")
    lines.append("    // TODO: Add implementation")
    lines.append("")
    lines.append("endmodule")
    return '\n'.join(lines)


inputs = [("a", 8), ("b", 8)]
outputs = [("sum", 8), ("carry", 1)]
verilog = build_verilog_module("adder_8bit", inputs, outputs)
print(verilog)

# ============================================
# PARSING DESIGN DESCRIPTIONS
# ============================================

print("\n" + "=" * 50)
print("PARSING DESIGN DESCRIPTIONS")
print("=" * 50)


def parse_design_description(description):
    """Extract design information from natural language"""
    desc = description.lower()
    result = {
        "original": description,
        "component": "unknown",
        "bit_width": 8,
        "has_clock": False,
        "has_reset": False,
        "operations": []
    }

    components = {
        "adder": ["adder", "add"],
        "counter": ["counter", "count"],
        "alu": ["alu", "arithmetic"],
        "multiplexer": ["mux", "multiplexer"],
        "register": ["register", "reg", "flip-flop"]
    }

    for comp, keywords in components.items():
        for kw in keywords:
            if kw in desc:
                result["component"] = comp
                break
        if result["component"] != "unknown":
            break

    width_patterns = [
        r'(\d+)[-\s]bit',
        r'bit[-\s]width[:\s](\d+)',
    ]

    for pattern in width_patterns:
        match = re.search(pattern, desc)
        if match:
            result["bit_width"] = int(match.group(1))
            break

    result["has_clock"] = any(word in desc for word in ["clock", "clk"])
    result["has_reset"] = any(word in desc for word in ["reset", "rst"])

    ops = ["add", "sub", "and", "or", "xor", "not"]
    for op in ops:
        if op in desc:
            result["operations"].append(op.upper())

    return result


test_descriptions = [
    "Create an 8-bit adder with clock",
    "Design a 16-bit counter with reset",
    "Build a 32-bit ALU with ADD, SUB, AND operations",
    "Make a 4-bit register with clock and reset"
]

for desc in test_descriptions:
    print(f"\nInput: {desc}")
    result = parse_design_description(desc)
    print(f"Parsed: {result['component']} ({result['bit_width']}bit)")
    print(f"Clock: {result['has_clock']}, Reset: {result['has_reset']}")
    if result['operations']:
        print(f"Ops: {result['operations']}")
