# day4_files.py - File Operations

import os

# ============================================
# WRITING TO FILES (BASIC)
# ============================================

print("Writing to file...")
with open('test.txt', 'w') as file:
    file.write('Hello, RTL-Gen AII!\n')
    file.write('This is my first file.\n')
    file.write('Bit width: 8\n')

print("File written successfully!")

if os.path.exists('test.txt'):
    print(f"File size: {os.path.getsize('test.txt')} bytes")

# ============================================
# READING FROM FILES
# ============================================

print("\n" + "=" * 50)
print("READING FILES")
print("=" * 50)

with open('test.txt', 'r') as file:
    content = file.read()
    print("Full content:")
    print(content)

print("Reading line by line:")
with open('test.txt', 'r') as file:
    line_number = 1
    for line in file:
        print(f"Line {line_number}: {line.strip()}")
        line_number += 1

with open('test.txt', 'r') as file:
    lines = file.readlines()
    print(f"\nAll lines as list: {lines}")

# ============================================
# APPENDING TO FILES
# ============================================

print("\n" + "=" * 50)
print("APPENDING TO FILES")
print("=" * 50)

with open('test.txt', 'a') as file:
    file.write('This line is appended!\n')
    file.write('Another appended line.\n')

with open('test.txt', 'r') as file:
    print("File after appending:")
    print(file.read())

# ============================================
# WRITING VERILOG CODE TO FILE
# ============================================

print("\n" + "=" * 50)
print("WRITING VERILOG CODE")
print("=" * 50)

verilog_code = """// 8-bit Adder
// Generated by RTL-Gen AII

module adder_8bit(
    input [7:0] a,
    input [7:0] b,
    output [7:0] sum,
    output carry
);
    assign {carry, sum} = a + b;
endmodule
"""

filename = 'adder_8bit.v'
with open(filename, 'w') as f:
    f.write(verilog_code)

print(f"Verilog code written to {filename}")

with open(filename, 'r') as f:
    print("\nVerification - File contents:")
    print(f.read())

# ============================================
# CHECKING IF FILES EXIST
# ============================================

print("\n" + "=" * 50)
print("FILE EXISTENCE CHECKING")
print("=" * 50)

files_to_check = ['adder_8bit.v', 'test.txt', 'nonexistent.txt']

for file in files_to_check:
    if os.path.exists(file):
        size = os.path.getsize(file)
        print(f"✓ {file} exists ({size} bytes)")
    else:
        print(f"✗ {file} does not exist")

# ============================================
# WORKING WITH DIRECTORIES
# ============================================

print("\n" + "=" * 50)
print("DIRECTORY OPERATIONS")
print("=" * 50)

dir_name = 'generated_designs'
if not os.path.exists(dir_name):
    os.mkdir(dir_name)
    print(f"Created directory: {dir_name}/")
else:
    print(f"Directory {dir_name}/ already exists")

nested_dir = os.path.join('generated_designs', 'rtl', 'adder')
os.makedirs(nested_dir, exist_ok=True)
print(f"Created nested directory: {nested_dir}/")

print("\nContents of current directory:")
for item in os.listdir('.'):
    if os.path.isdir(item):
        print(f"  📁 {item}/")
    else:
        size = os.path.getsize(item)
        print(f"  📄 {item} ({size} bytes)")

# ============================================
# PRACTICAL: SAVE DESIGN TO PROPER STRUCTURE
# ============================================


def save_verilog_design(module_name, verilog_code, testbench_code=None):
    """Save a complete design with proper directory structure"""
    base_dir = os.path.join('generated_designs', module_name)
    os.makedirs(base_dir, exist_ok=True)

    rtl_dir = os.path.join(base_dir, 'rtl')
    tb_dir = os.path.join(base_dir, 'testbench')
    sim_dir = os.path.join(base_dir, 'simulation')

    os.makedirs(rtl_dir, exist_ok=True)
    os.makedirs(tb_dir, exist_ok=True)
    os.makedirs(sim_dir, exist_ok=True)

    rtl_path = os.path.join(rtl_dir, f'{module_name}.v')
    with open(rtl_path, 'w') as f:
        f.write(verilog_code)
    print(f"✓ Saved RTL: {rtl_path}")

    if testbench_code:
        tb_path = os.path.join(tb_dir, f'{module_name}_tb.v')
        with open(tb_path, 'w') as f:
            f.write(testbench_code)
        print(f"✓ Saved testbench: {tb_path}")

    readme_path = os.path.join(base_dir, 'README.md')
    readme_content = f"""# {module_name}

Generated on: 2026-03-18

## Directory Structure
- `rtl/` - RTL source files
- `testbench/` - Testbench files
- `simulation/` - Simulation outputs
"""
    with open(readme_path, 'w') as f:
        f.write(readme_content)
    print(f"✓ Saved README: {readme_path}")


test_tb = """module adder_8bit_tb;
    reg [7:0] a, b;
    wire [7:0] sum;
    wire carry;

    adder_8bit dut(.a(a), .b(b), .sum(sum), .carry(carry));

    initial begin
        $monitor("a=%d b=%d sum=%d carry=%b", a, b, sum, carry);
        a = 10; b = 20; #10;
        a = 50; b = 50; #10;
        a = 200; b = 100; #10;
        $finish;
    end
endmodule"""

save_verilog_design("adder_8bit", verilog_code, test_tb)
