# day4_practice.py

import os
import json
import datetime

# ============================================
# EXERCISE 1: File Backup System
# ============================================


def backup_file(filename):
    """Create backup of file. Returns: (success, backup_name or error)"""
    if not os.path.exists(filename):
        return False, f"File '{filename}' does not exist"

    backup_name = filename + ".bak"
    try:
        with open(filename, 'r') as src:
            content = src.read()
        with open(backup_name, 'w') as dst:
            dst.write(content)
        return True, backup_name
    except Exception as e:
        return False, str(e)


# Create a test file first
with open("adder_8bit.v", "w") as f:
    f.write("module adder_8bit(); endmodule\n")

success, result = backup_file("adder_8bit.v")
print(f"Backup: {result}")

# ============================================
# EXERCISE 2: Design Description Parser
# ============================================


def parse_and_save(description, output_file):
    """Parse description and save to JSON"""
    import re
    desc = description.lower()

    comp = "unknown"
    for c in ["adder", "counter", "alu", "mux"]:
        if c in desc:
            comp = c
            break

    width = 8
    match = re.search(r'(\d+)[-\s]bit', desc)
    if match:
        width = int(match.group(1))

    result = {
        "description": description,
        "component": comp,
        "bit_width": width,
        "has_clock": "clock" in desc or "clk" in desc,
        "has_reset": "reset" in desc or "rst" in desc
    }

    with open(output_file, 'w') as f:
        json.dump(result, f, indent=2)

    print(f"Saved parsed design to {output_file}")
    return result


parse_and_save("Create a 16-bit ALU with ADD, SUB", "design.json")

# ============================================
# EXERCISE 3: Multi-File Generator
# ============================================


def generate_adder_family():
    """Generate adders for 4, 8, 16 bits"""
    bit_widths = [4, 8, 16]

    os.makedirs("outputs", exist_ok=True)

    for width in bit_widths:
        code = f"""// adder_{width}bit.v
// Generated by RTL-Gen AII

module adder_{width}bit(
    input [{width-1}:0] a,
    input [{width-1}:0] b,
    output [{width-1}:0] sum,
    output carry
);
    assign {{carry, sum}} = a + b;
endmodule
"""
        filename = os.path.join("outputs", f"adder_{width}bit.v")
        with open(filename, 'w') as f:
            f.write(code)
        print(f"✓ Generated {filename}")


generate_adder_family()

# ============================================
# EXERCISE 4: Log File Creator
# ============================================


def log_message(message, level="INFO"):
    """Append message to log file with timestamp"""
    timestamp = datetime.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    formatted = f"[{timestamp}] {level}: {message}\n"

    os.makedirs("logs", exist_ok=True)
    with open(os.path.join("logs", "rtl_gen.log"), 'a') as f:
        f.write(formatted)
    print(f"Logged: {formatted.strip()}")


log_message("Design generation started")
log_message("Bit width 8 not power of 2", "WARNING")
log_message("Failed to write file", "ERROR")

# ============================================
# EXERCISE 5: Template System
# ============================================

template = """// {{module_name}}.v
// Bit width: {{bit_width}}

module {{module_name}}(
    input [{{bit_width_minus_1}}:0] a,
    input [{{bit_width_minus_1}}:0] b,
    output [{{bit_width_minus_1}}:0] sum
);
    assign sum = a + b;
endmodule
"""

with open("template.v", "w") as f:
    f.write(template)


def generate_from_template(template_file, replacements, output_file):
    """Generate file from template"""
    with open(template_file, 'r') as f:
        content = f.read()

    for key, value in replacements.items():
        content = content.replace("{{" + key + "}}", str(value))

    with open(output_file, 'w') as f:
        f.write(content)
    print(f"✓ Generated {output_file} from template")


replacements = {
    "module_name": "adder_8bit",
    "bit_width": "8",
    "bit_width_minus_1": "7"
}

generate_from_template("template.v", replacements, "adder_8bit_from_template.v")

with open("adder_8bit_from_template.v", 'r') as f:
    print("\nGenerated from template:")
    print(f.read())
