FROM openroad/ubuntu22.04-dev
RUN apt-get update && apt-get install -y x11vnc xvfb openbox novnc websockify net-tools && rm -rf /var/lib/apt/lists/*
RUN mkdir -p /root/.vnc && x11vnc -storepasswd openroad /root/.vnc/passwd
EXPOSE 6080
CMD bash -c "Xvfb :1 -screen 0 1920x1080x24 & \
  sleep 2 && openbox --display :1 & \
  sleep 1 && x11vnc -display :1 -rfbauth /root/.vnc/passwd -forever -shared & \
  sleep 2 && websockify --web /usr/share/novnc/ 6080 localhost:5900"
