"""
sdc_generator.py — Smart SDC Timing Constraint Generator
RTL-Gen AI

Analyses the RTL to determine appropriate clock period and
generates a proper SDC file instead of the hardcoded 10ns default.

Usage in full_flow.py:
    from sdc_generator import generate_sdc
    sdc_path = generate_sdc(rtl_path, design_name, run_dir)
"""

import re
from pathlib import Path
from typing import Optional

# Default periods by design type (nanoseconds)
_PERIOD_MAP = {
    "memory":     15.0,   # SRAM is slow
    "sram":       15.0,
    "fifo":       12.0,
    "uart":       20.0,   # UART runs at slow baud rates
    "i2c":        20.0,
    "multiplier": 12.0,   # multipliers have long paths
    "mult":       12.0,
    "pipeline":   8.0,    # pipelines can run fast
    "alu":        10.0,
    "adder":      10.0,
    "counter":    8.0,
    "shift":      8.0,
    "pwm":        10.0,
    "crc":        10.0,
}

def estimate_clock_period(rtl_code: str, module_name: str) -> float:
    """Estimate appropriate clock period from RTL analysis."""
    name_lower = module_name.lower()
    for keyword, period in _PERIOD_MAP.items():
        if keyword in name_lower:
            return period

    # Count always blocks — more blocks = more complex = slower
    always_count = len(re.findall(r"\balways\b", rtl_code))
    assign_count = len(re.findall(r"\bassign\b", rtl_code))
    case_count   = len(re.findall(r"\bcase\b",   rtl_code))

    # Rough heuristic
    complexity = always_count + case_count * 0.5 + assign_count * 0.2
    if complexity > 20: return 15.0
    if complexity > 10: return 12.0
    if complexity > 5:  return 10.0
    return 8.0


def generate_sdc(
    rtl_path:    Path,
    module_name: str,
    output_dir:  Path,
) -> Path:
    """
    Generate a timing constraints SDC file for a design.
    Returns the path to the written SDC file.
    """
    rtl_code = rtl_path.read_text(errors="replace") if rtl_path.exists() else ""
    period   = estimate_clock_period(rtl_code, module_name)

    # Detect clock port name
    clk_match = re.search(r"\binput\b.*?\b(clk\w*|clock\w*|ck\w*)\b", rtl_code)
    clk_port  = clk_match.group(1) if clk_match else "clk"

    # Detect reset port
    rst_match = re.search(r"\binput\b.*?\b(reset_n|rst_n|resetn|arst_n)\b", rtl_code)
    rst_port  = rst_match.group(1) if rst_match else None

    sdc = f"""\
# SDC Timing Constraints — {module_name}
# Generated by RTL-Gen AI sdc_generator.py
# Clock period: {period} ns ({1000/period:.1f} MHz target)

create_clock -name clk -period {period} [get_ports {clk_port}]

# Input/output delays (25% of period)
set_input_delay  -clock clk {period * 0.25:.2f} [all_inputs]
set_output_delay -clock clk {period * 0.25:.2f} [all_outputs]

# False paths on async signals
"""
    if rst_port:
        sdc += f"set_false_path -from [get_ports {rst_port}]\n"

    sdc += f"""
# Clock uncertainty (jitter + skew)
set_clock_uncertainty 0.1 [get_clocks clk]

# Disable timing on constants
set_false_path -from [get_ports VDD] 2>/dev/null || true
set_false_path -from [get_ports GND] 2>/dev/null || true
"""

    sdc_path = output_dir / f"{module_name}.sdc"
    output_dir.mkdir(parents=True, exist_ok=True)
    sdc_path.write_text(sdc, encoding="utf-8")
    return sdc_path
