// Module: adder_4bit
// Generated by RTL-Gen AII (Mock) on 2026-03-20

module adder_4bit(
    input  [3:0] a,
    input  [3:0] b,
    output [3:0] sum,
    output               carry
);
    assign {carry, sum} = a + b;
endmodule