//==============================================================================
// Module: adder_8bit
// Description: 4-bit adder with carry
//
// Generated by: RTL-Gen AII
// Date: 2026-06-04 23:03:24
//==============================================================================

// Module: adder_8bit
// Generated by RTL-Gen AII (Mock) on 2026-06-04

module adder_8bit(
  input  [7:0] a,
  input  [7:0] b,
  output [7:0] sum,
  output               carry
);
  assign {carry, sum} = a + b;
endmodule
