# template_generator.py
"""Verilog template generator for RTL Assistant"""


class TemplateGenerator:
    """Generate Verilog code from parsed design specs"""

    def __init__(self):
        self.templates = {
            "adder": self._adder_template,
            "counter": self._counter_template,
            "alu": self._alu_template,
            "multiplexer": self._mux_template,
            "register": self._register_template,
            "generic": self._generic_template
        }

    def generate(self, parsed):
        """Generate Verilog code from parsed specs"""
        component = parsed["component"]
        if component in self.templates:
            return self.templates[component](parsed)
        else:
            return self.templates["generic"](parsed)

    def _adder_template(self, parsed):
        width = parsed["bit_width"]
        name = parsed.get("module_name", f"adder_{width}bit")
        return f"""// {name}.v
// Generated by RTL Assistant
// Component: {parsed['component']}
// Bit width: {width}

module {name}(
    input [{width-1}:0] a,
    input [{width-1}:0] b,
    output [{width-1}:0] sum,
    output carry
);
    // {width}-bit addition with carry
    assign {{carry, sum}} = a + b;

endmodule
"""

    def _counter_template(self, parsed):
        width = parsed["bit_width"]
        name = parsed.get("module_name", f"counter_{width}bit")
        has_reset = parsed.get("has_reset", True)
        reset_sens = " or posedge reset" if has_reset else ""
        reset_port = "    input reset,\n" if has_reset else ""
        reset_block = "        if (reset)\n            count <= {}'b0;\n        else if".format(width)
        no_reset_block = "        if"

        return f"""// {name}.v
// Generated by RTL Assistant
// Component: {parsed['component']}
// Bit width: {width}

module {name}(
    input clk,
{reset_port}    input enable,
    output reg [{width-1}:0] count
);
    always @(posedge clk{reset_sens}) begin
{reset_block if has_reset else no_reset_block} (enable)
            count <= count + 1'b1;
    end

endmodule
"""

    def _alu_template(self, parsed):
        width = parsed["bit_width"]
        name = parsed.get("module_name", f"alu_{width}bit")
        ops = parsed.get("operations", ["ADD", "SUB", "AND", "OR"])
        op_width = max(3, len(ops).bit_length())

        case_items = []
        for i, op in enumerate(ops):
            case_items.append(
                f"            {op_width}'d{i}: result = a {self._op_to_symbol(op)} b;"
            )
        case_str = "\n".join(case_items)

        return f"""// {name}.v
// Generated by RTL Assistant
// Component: {parsed['component']}
// Bit width: {width}
// Operations: {', '.join(ops)}

module {name}(
    input [{width-1}:0] a,
    input [{width-1}:0] b,
    input [{op_width-1}:0] opcode,
    output reg [{width-1}:0] result,
    output reg zero
);
    always @(*) begin
        case(opcode)
{case_str}
            default: result = {width}'b0;
        endcase
        zero = (result == {width}'b0);
    end

endmodule
"""

    def _op_to_symbol(self, op):
        symbols = {
            "ADD": "+", "SUB": "-", "AND": "&",
            "OR": "|", "XOR": "^", "NOT": "~"
        }
        return symbols.get(op, "+")

    def _mux_template(self, parsed):
        width = parsed["bit_width"]
        name = parsed.get("module_name", f"mux_{width}bit")
        return f"""// {name}.v
// Generated by RTL Assistant
// Component: {parsed['component']}
// Bit width: {width}

module {name}(
    input [{width-1}:0] in0,
    input [{width-1}:0] in1,
    input sel,
    output [{width-1}:0] out
);
    assign out = sel ? in1 : in0;

endmodule
"""

    def _register_template(self, parsed):
        width = parsed["bit_width"]
        name = parsed.get("module_name", f"register_{width}bit")
        return f"""// {name}.v
// Generated by RTL Assistant
// Component: {parsed['component']}
// Bit width: {width}

module {name}(
    input clk,
    input reset,
    input [{width-1}:0] d,
    output reg [{width-1}:0] q
);
    always @(posedge clk or posedge reset) begin
        if (reset)
            q <= {width}'b0;
        else
            q <= d;
    end

endmodule
"""

    def _generic_template(self, parsed):
        width = parsed["bit_width"]
        name = parsed.get("module_name", f"design_{width}bit")
        return f"""// {name}.v
// Generated by RTL Assistant
// Component: {parsed['component']}
// Bit width: {width}

module {name}(
    input clk,
    input reset,
    input [{width-1}:0] data_in,
    output reg [{width-1}:0] data_out
);
    always @(posedge clk or posedge reset) begin
        if (reset)
            data_out <= {width}'b0;
        else
            data_out <= data_in;
    end

endmodule
"""
