/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module adder_8bit(clk, reset_n, a, b, sum);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  wire _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  wire _26_;
  wire _27_;
  wire _28_;
  wire _29_;
  wire _30_;
  wire _31_;
  wire _32_;
  input [7:0] a;
  wire [7:0] a;
  input [7:0] b;
  wire [7:0] b;
  input clk;
  wire clk;
  input reset_n;
  wire reset_n;
  output [8:0] sum;
  wire [8:0] sum;
  sky130_fd_sc_hd__and2_0 _33_ (
    .A(b[0]),
    .B(a[0]),
    .X(_09_)
  );
  sky130_fd_sc_hd__o21ai_0 _34_ (
    .A1(b[0]),
    .A2(a[0]),
    .B1(reset_n),
    .Y(_10_)
  );
  sky130_fd_sc_hd__nor2_1 _35_ (
    .A(_09_),
    .B(_10_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__xor2_1 _36_ (
    .A(b[1]),
    .B(a[1]),
    .X(_11_)
  );
  sky130_fd_sc_hd__o21ai_0 _37_ (
    .A1(_09_),
    .A2(_11_),
    .B1(reset_n),
    .Y(_12_)
  );
  sky130_fd_sc_hd__a21oi_1 _38_ (
    .A1(_09_),
    .A2(_11_),
    .B1(_12_),
    .Y(_01_)
  );
  sky130_fd_sc_hd__maj3_1 _39_ (
    .A(b[1]),
    .B(a[1]),
    .C(_09_),
    .X(_13_)
  );
  sky130_fd_sc_hd__xor2_1 _40_ (
    .A(b[2]),
    .B(a[2]),
    .X(_14_)
  );
  sky130_fd_sc_hd__o21ai_0 _41_ (
    .A1(_13_),
    .A2(_14_),
    .B1(reset_n),
    .Y(_15_)
  );
  sky130_fd_sc_hd__a21oi_1 _42_ (
    .A1(_13_),
    .A2(_14_),
    .B1(_15_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__maj3_1 _43_ (
    .A(b[2]),
    .B(a[2]),
    .C(_13_),
    .X(_16_)
  );
  sky130_fd_sc_hd__xor2_1 _44_ (
    .A(b[3]),
    .B(a[3]),
    .X(_17_)
  );
  sky130_fd_sc_hd__o21ai_0 _45_ (
    .A1(_16_),
    .A2(_17_),
    .B1(reset_n),
    .Y(_18_)
  );
  sky130_fd_sc_hd__a21oi_1 _46_ (
    .A1(_16_),
    .A2(_17_),
    .B1(_18_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__maj3_1 _47_ (
    .A(b[3]),
    .B(a[3]),
    .C(_16_),
    .X(_19_)
  );
  sky130_fd_sc_hd__xor2_1 _48_ (
    .A(b[4]),
    .B(a[4]),
    .X(_20_)
  );
  sky130_fd_sc_hd__o21ai_0 _49_ (
    .A1(_19_),
    .A2(_20_),
    .B1(reset_n),
    .Y(_21_)
  );
  sky130_fd_sc_hd__a21oi_1 _50_ (
    .A1(_19_),
    .A2(_20_),
    .B1(_21_),
    .Y(_04_)
  );
  sky130_fd_sc_hd__maj3_1 _51_ (
    .A(b[4]),
    .B(a[4]),
    .C(_19_),
    .X(_22_)
  );
  sky130_fd_sc_hd__xor2_1 _52_ (
    .A(b[5]),
    .B(a[5]),
    .X(_23_)
  );
  sky130_fd_sc_hd__o21ai_0 _53_ (
    .A1(_22_),
    .A2(_23_),
    .B1(reset_n),
    .Y(_24_)
  );
  sky130_fd_sc_hd__a21oi_1 _54_ (
    .A1(_22_),
    .A2(_23_),
    .B1(_24_),
    .Y(_05_)
  );
  sky130_fd_sc_hd__maj3_1 _55_ (
    .A(b[5]),
    .B(a[5]),
    .C(_22_),
    .X(_25_)
  );
  sky130_fd_sc_hd__xor2_1 _56_ (
    .A(b[6]),
    .B(a[6]),
    .X(_26_)
  );
  sky130_fd_sc_hd__o21ai_0 _57_ (
    .A1(_25_),
    .A2(_26_),
    .B1(reset_n),
    .Y(_27_)
  );
  sky130_fd_sc_hd__a21oi_1 _58_ (
    .A1(_25_),
    .A2(_26_),
    .B1(_27_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__maj3_1 _59_ (
    .A(b[6]),
    .B(a[6]),
    .C(_25_),
    .X(_28_)
  );
  sky130_fd_sc_hd__nand2_1 _60_ (
    .A(b[7]),
    .B(a[7]),
    .Y(_29_)
  );
  sky130_fd_sc_hd__xor2_1 _61_ (
    .A(b[7]),
    .B(a[7]),
    .X(_30_)
  );
  sky130_fd_sc_hd__nand2_1 _62_ (
    .A(_28_),
    .B(_30_),
    .Y(_31_)
  );
  sky130_fd_sc_hd__o21ai_0 _63_ (
    .A1(_28_),
    .A2(_30_),
    .B1(reset_n),
    .Y(_32_)
  );
  sky130_fd_sc_hd__a21oi_1 _64_ (
    .A1(_28_),
    .A2(_30_),
    .B1(_32_),
    .Y(_07_)
  );
  sky130_fd_sc_hd__a21boi_0 _65_ (
    .A1(_29_),
    .A2(_31_),
    .B1_N(reset_n),
    .Y(_08_)
  );
  sky130_fd_sc_hd__dfxtp_1 _66_ (
    .CLK(clk),
    .D(_00_),
    .Q(sum[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _67_ (
    .CLK(clk),
    .D(_01_),
    .Q(sum[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _68_ (
    .CLK(clk),
    .D(_02_),
    .Q(sum[2])
  );
  sky130_fd_sc_hd__dfxtp_1 _69_ (
    .CLK(clk),
    .D(_03_),
    .Q(sum[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _70_ (
    .CLK(clk),
    .D(_04_),
    .Q(sum[4])
  );
  sky130_fd_sc_hd__dfxtp_1 _71_ (
    .CLK(clk),
    .D(_05_),
    .Q(sum[5])
  );
  sky130_fd_sc_hd__dfxtp_1 _72_ (
    .CLK(clk),
    .D(_06_),
    .Q(sum[6])
  );
  sky130_fd_sc_hd__dfxtp_1 _73_ (
    .CLK(clk),
    .D(_07_),
    .Q(sum[7])
  );
  sky130_fd_sc_hd__dfxtp_1 _74_ (
    .CLK(clk),
    .D(_08_),
    .Q(sum[8])
  );
endmodule
