/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module my_design(clk, reset, data_in, data_out);
  input clk;
  wire clk;
  input [7:0] data_in;
  wire [7:0] data_in;
  output [7:0] data_out;
  wire [7:0] data_out;
  input reset;
  wire reset;
  assign data_out = data_in;
endmodule
