// Module: adder_8bit
// Generated by RTL-Gen AII (Mock) on 2026-03-21

module adder_8bit(
    input  [7:0] a,
    input  [7:0] b,
    output [7:0] sum,
    output               carry
);
    assign {carry, sum} = a + b;
endmodule