// adder_8bit.v
// Generated by RTL Assistant
// Component: adder
// Bit width: 8

module adder_8bit(
    input [7:0] a,
    input [7:0] b,
    output [7:0] sum,
    output carry
);
    // 8-bit addition with carry
    assign {carry, sum} = a + b;

endmodule
