"""
Code Formatter for RTL-Gen AII.
Cleans and standardizes Verilog code formatting.

Features:
- Consistent indentation
- Whitespace cleanup
- File header generation
- Line ending normalization
"""

import re
from datetime import datetime
from typing import Optional


class CodeFormatter:
    """Format and clean Verilog code."""

    def __init__(self, indent_size=2, debug=False):
        self.indent_size = indent_size
        self.debug = debug

    def format(self, code, module_name=None, description=None, add_header=True):
        """
        Format Verilog code.

        Args:
            code: Raw Verilog code
            module_name: For the header
            description: For the header
            add_header: Whether to prepend a header comment

        Returns:
            str: Formatted code
        """
        if not code.strip():
            return ""

        code = self._clean_whitespace(code)
        code = self._standardize_indentation(code)

        if add_header:
            if not module_name:
                module_name = self._extract_module_name(code)
            header = self._generate_header(module_name, description)
            code = header + "\n\n" + code

        code = self._final_cleanup(code)
        return code

    def _clean_whitespace(self, code):
        """Remove trailing spaces, normalize line endings, collapse blank lines."""
        code = code.replace('\r\n', '\n')
        lines = [line.rstrip() for line in code.split('\n')]

        cleaned = []
        prev_blank = False
        for line in lines:
            is_blank = len(line.strip()) == 0
            if is_blank:
                if not prev_blank:
                    cleaned.append("")
                prev_blank = True
            else:
                cleaned.append(line)
                prev_blank = False
        return '\n'.join(cleaned)

    def _standardize_indentation(self, code):
        """Apply consistent indentation."""
        lines = code.split('\n')
        formatted = []
        indent = 0
        in_module = False
        in_port_list = False

        for line in lines:
            stripped = line.strip()
            if not stripped:
                formatted.append("")
                continue

            # Dedent before these keywords
            if stripped.startswith('endmodule'):
                indent = 0
                in_module = False
            elif stripped.startswith('end') and indent > 0:
                indent -= 1

            # Port list closing: ); on its own line
            if stripped == ');' and in_port_list:
                in_port_list = False
                indent = 0
                formatted.append(' ' * (indent * self.indent_size) + stripped)
                indent = 1  # body starts after port list
                continue

            formatted.append(' ' * (indent * self.indent_size) + stripped)

            # Indent triggers after this line
            if stripped.startswith('module'):
                in_module = True
                if '(' in stripped and ');' not in stripped:
                    # Multi-line port list
                    in_port_list = True
                    indent = 1
                elif ');' in stripped:
                    # Single-line module(ports);
                    indent = 1
                else:
                    # module name; (no ports)
                    indent = 1
            elif re.match(r'^(always|initial)\b', stripped):
                if 'begin' in stripped:
                    indent += 1
            elif stripped == 'begin':
                indent += 1

        return '\n'.join(formatted)

    def _generate_header(self, module_name=None, description=None):
        sep = "=" * 78
        lines = [
            f"//{sep}",
            f"// Module: {module_name or 'Unknown'}",
        ]
        if description:
            lines.append(f"// Description: {description}")
        lines.extend([
            f"//",
            f"// Generated by: RTL-Gen AII",
            f"// Date: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}",
            f"//{sep}",
        ])
        return '\n'.join(lines)

    def _extract_module_name(self, code):
        match = re.search(r'module\s+(\w+)', code, re.IGNORECASE)
        return match.group(1) if match else None

    def _final_cleanup(self, code):
        lines = code.split('\n')
        while lines and not lines[0].strip():
            lines.pop(0)
        code = '\n'.join(lines)
        if not code.endswith('\n'):
            code += '\n'
        return code


if __name__ == "__main__":
    print("Code Formatter Self-Test\n" + "=" * 60)
    fmt = CodeFormatter(indent_size=2)

    messy = """
module adder(
input a,
      input b,
output sum);

assign sum=a+b;

endmodule
"""
    clean = fmt.format(messy, description="Simple adder")
    print("Formatted output:")
    print(clean)
    print("=" * 60 + "\nSelf-test passed ✓")
