"""
Mock LLM Client for RTL-Gen AII.
Simulates LLM responses for testing without API calls.
"""

import time
import random
from datetime import datetime


class MockLLM:
    """Simulate responses from DeepSeek-V3.2 without real API calls."""

    def __init__(self, delay=0.5, error_rate=0.0):
        self.delay = delay
        self.error_rate = error_rate
        self.call_count = 0

    def generate(self, prompt, **kwargs):
        """Generate a simulated response."""
        self.call_count += 1
        if self.delay > 0:
            time.sleep(self.delay)
        if random.random() < self.error_rate:
            return {'error': {'message': 'Simulated API error', 'type': 'mock_error'}}

        prompt_lower = prompt.lower()
        if 'adder' in prompt_lower:
            content = self._adder(prompt)
        elif 'counter' in prompt_lower:
            content = self._counter()
        elif 'alu' in prompt_lower:
            content = self._alu()
        else:
            content = self._generic()

        return {
            'choices': [{'message': {'content': content}}],
            'usage': {'prompt_tokens': 100, 'completion_tokens': 200, 'total_tokens': 300},
            'model': 'mock-llm',
            'id': f'mock_{self.call_count}'
        }

    def _adder(self, prompt):
        width = 8
        for w in [64, 32, 16, 8, 4]:
            if f"{w}-bit" in prompt or f"{w} bit" in prompt:
                width = w
                break
        today = datetime.now().strftime('%Y-%m-%d')
        return f"""Here's the Verilog code for a {width}-bit adder:

```verilog
// Module: adder_{width}bit
// Generated by RTL-Gen AII (Mock) on {today}

module adder_{width}bit(
    input  [{width-1}:0] a,
    input  [{width-1}:0] b,
    output [{width-1}:0] sum,
    output               carry
);
    assign {{carry, sum}} = a + b;
endmodule
```

```verilog
`timescale 1ns/1ps

module adder_{width}bit_tb;
    reg  [{width-1}:0] a, b;
    wire [{width-1}:0] sum;
    wire               carry;

    adder_{width}bit dut(.*);

    initial begin
        $dumpfile("adder.vcd");
        $dumpvars(0, adder_{width}bit_tb);
        a = {width}'d10; b = {width}'d20; #10;
        $display("10 + 20 = %d carry=%b", sum, carry);
        a = {width}'d255; b = {width}'d1; #10;
        $display("255 + 1 = %d carry=%b", sum, carry);
        $finish;
    end
endmodule
```"""

    def _counter(self):
        return """Here's the Verilog code for an 8-bit counter:

```verilog
module counter_8bit(
    input        clk,
    input        reset,
    input        enable,
    output reg [7:0] count
);
    always @(posedge clk) begin
        if (reset)
            count <= 8'b0;
        else if (enable)
            count <= count + 1;
    end
endmodule
```

```verilog
`timescale 1ns/1ps

module counter_8bit_tb;
    reg clk, reset, enable;
    wire [7:0] count;

    counter_8bit dut(.*);

    initial begin clk = 0; forever #5 clk = ~clk; end

    initial begin
        $dumpfile("counter.vcd");
        $dumpvars(0, counter_8bit_tb);
        reset = 1; enable = 0;
        #20 reset = 0; enable = 1;
        #100 $finish;
    end
endmodule
```"""

    def _alu(self):
        return """Here's the Verilog code for an 8-bit ALU:

```verilog
module alu_8bit(
    input  [7:0] a, b,
    input  [1:0] op,
    output reg [7:0] result,
    output reg       zero
);
    localparam ADD = 2'b00, SUB = 2'b01, AND_OP = 2'b10, OR_OP = 2'b11;

    always @(*) begin
        case(op)
            ADD:    result = a + b;
            SUB:    result = a - b;
            AND_OP: result = a & b;
            OR_OP:  result = a | b;
            default: result = 8'b0;
        endcase
        zero = (result == 8'b0);
    end
endmodule
```

```verilog
`timescale 1ns/1ps

module alu_8bit_tb;
    reg [7:0] a, b;
    reg [1:0] op;
    wire [7:0] result;
    wire zero;

    alu_8bit dut(.*);

    initial begin
        $dumpfile("alu.vcd");
        $dumpvars(0, alu_8bit_tb);
        a = 8'd15; b = 8'd10;
        op = 2'b00; #10; $display("ADD: %d", result);
        op = 2'b01; #10; $display("SUB: %d", result);
        op = 2'b10; #10; $display("AND: %h", result);
        op = 2'b11; #10; $display("OR:  %h", result);
        $finish;
    end
endmodule
```"""

    def _generic(self):
        return """Here's a generic Verilog module:

```verilog
module custom_module(
    input        clk,
    input        reset,
    input  [7:0] data_in,
    output reg [7:0] data_out
);
    always @(posedge clk) begin
        if (reset) data_out <= 8'b0;
        else       data_out <= data_in;
    end
endmodule
```"""

    def get_stats(self):
        return {'call_count': self.call_count, 'delay': self.delay}


def get_mock_llm(delay=0.5, error_rate=0.0):
    return MockLLM(delay=delay, error_rate=error_rate)


if __name__ == "__main__":
    print("Mock LLM Self-Test\n")
    mock = MockLLM(delay=0.1)

    r = mock.generate("Generate an 8-bit adder")
    print(f"Adder: {len(r['choices'][0]['message']['content'])} chars ✓")

    r = mock.generate("Generate a 16-bit counter with reset")
    print(f"Counter: {len(r['choices'][0]['message']['content'])} chars ✓")

    r = mock.generate("Build a 32-bit ALU")
    print(f"ALU: {len(r['choices'][0]['message']['content'])} chars ✓")

    print(f"Stats: {mock.get_stats()}")
    print("Self-test complete ✓")
