#!/usr/bin/env python3
"""
validate_pipeline_outputs.py
=============================
Validates that all pipeline stage outputs are REAL files, not stubs or fakes.
Checks file structure, content, and generates proof report.

Run from project root:
    python python/validate_pipeline_outputs.py
"""

import sys
import json
from pathlib import Path
from datetime import datetime
import logging

logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s | %(levelname)s | %(message)s'
)
logger = logging.getLogger(__name__)

PROJECT_ROOT = Path(__file__).resolve().parent.parent
VALIDATION_DIR = PROJECT_ROOT / "validation"
INTEGRATION_TESTS_DIR = VALIDATION_DIR / "integration_tests"

# Minimum file sizes to prove they're not stubs
MIN_NETLIST_SIZE = 2000  # bytes
MIN_DEF_SIZE = 5000  # bytes
MIN_REPORT_SIZE = 100  # bytes

class OutputValidator:
    """Validates pipeline output files are real, not fakes."""
    
    def __init__(self):
        self.report = {
            "timestamp": datetime.now().isoformat(),
            "test_run": None,
            "stages": {},
            "summary": {
                "total_stages_checked": 0,
                "real_outputs": 0,
                "fake_outputs": 0,
                "missing_outputs": 0,
            },
            "evidence": []
        }
    
    def find_latest_test(self):
        """Find the most recent integration test run."""
        test_dirs = sorted(
            INTEGRATION_TESTS_DIR.glob("pipeline_test_*"),
            key=lambda p: p.stat().st_mtime,
            reverse=True
        )
        if test_dirs:
            return test_dirs[0]
        return None
    
    def validate_netlist(self, netlist_path):
        """Validate Verilog synthesis netlist is real."""
        result = {
            "file": str(netlist_path),
            "exists": False,
            "real": False,
            "validation": {},
            "issues": []
        }
        
        if not netlist_path.exists():
            result["issues"].append("File does not exist")
            return result
        
        result["exists"] = True
        size = netlist_path.stat().st_size
        result["validation"]["file_size_bytes"] = size
        
        try:
            content = netlist_path.read_text(encoding="utf-8", errors="ignore")
            
            # Check for Yosys signature
            has_yosys = "Generated by Yosys" in content
            result["validation"]["has_yosys_signature"] = has_yosys
            if not has_yosys:
                result["issues"].append("Missing Yosys signature")
            
            # Check for module declaration
            has_module = "module " in content
            result["validation"]["has_module_declaration"] = has_module
            if not has_module:
                result["issues"].append("No module declaration found")
            
            # Check for Sky130 cells
            sky130_count = content.count("sky130_fd_sc_hd__")
            result["validation"]["sky130_cells_count"] = sky130_count
            if sky130_count == 0:
                result["issues"].append("No Sky130 cells found")
            
            # Check file size
            if size < MIN_NETLIST_SIZE:
                result["issues"].append(f"File too small ({size} bytes < {MIN_NETLIST_SIZE} minimum)")
            
            # Real output if passes all checks
            result["real"] = (
                has_yosys and 
                has_module and 
                sky130_count > 0 and 
                size >= MIN_NETLIST_SIZE
            )
            
            # Extract some cell instances as proof
            import re
            cells = re.findall(r'sky130_fd_sc_hd__(\w+)_\d', content)
            result["validation"]["cell_types_used"] = list(set(cells))[:5]
            
        except Exception as e:
            result["issues"].append(f"Error reading file: {e}")
        
        return result
    
    def validate_def_file(self, def_path, stage_name):
        """Validate DEF file (floorplan, placement, CTS, routing)."""
        result = {
            "file": str(def_path),
            "exists": False,
            "real": False,
            "validation": {},
            "issues": []
        }
        
        if not def_path.exists():
            result["issues"].append("File does not exist")
            return result
        
        result["exists"] = True
        size = def_path.stat().st_size
        result["validation"]["file_size_bytes"] = size
        result["validation"]["line_count"] = len(def_path.read_text().splitlines())
        
        try:
            content = def_path.read_text(encoding="utf-8", errors="ignore").upper()
            
            # Check DEF structure
            has_version = "VERSION" in content
            has_divider = "DIVIDERCHAR" in content
            has_design = "DESIGN" in content
            has_units = "UNITS" in content
            has_components = "COMPONENTS" in content
            
            result["validation"]["has_version"] = has_version
            result["validation"]["has_divider"] = has_divider
            result["validation"]["has_design"] = has_design
            result["validation"]["has_units"] = has_units
            result["validation"]["has_components"] = has_components
            
            if not (has_version and has_divider and has_design):
                result["issues"].append("Missing DEF header keywords")
            
            if not has_components:
                result["issues"].append("No COMPONENTS section found")
            
            # Check file size
            if size < MIN_DEF_SIZE:
                result["issues"].append(f"File too small ({size} bytes < {MIN_DEF_SIZE} minimum)")
            
            # Real output if passes validation
            result["real"] = (
                has_version and 
                has_divider and 
                has_design and 
                has_components and 
                size >= MIN_DEF_SIZE
            )
            
        except Exception as e:
            result["issues"].append(f"Error reading file: {e}")
        
        return result
    
    def validate_stage(self, test_dir, stage_num, stage_name, expected_files):
        """Validate all output files for a pipeline stage."""
        stage_dir = test_dir / f"{stage_num:02d}_{stage_name}"
        
        stage_result = {
            "stage": stage_name,
            "directory": str(stage_dir),
            "exists": stage_dir.exists(),
            "files": {},
            "passed": True,
        }
        
        if not stage_dir.exists():
            stage_result["passed"] = False
            return stage_result
        
        # Validate each expected file
        for file_info in expected_files:
            file_name = file_info["name"]
            file_path = stage_dir / file_name
            validator = file_info["validator"]
            
            if validator == "netlist":
                result = self.validate_netlist(file_path)
            elif validator == "def":
                result = self.validate_def_file(file_path, stage_name)
            else:
                result = {
                    "file": str(file_path),
                    "exists": file_path.exists(),
                    "real": file_path.exists(),
                }
            
            stage_result["files"][file_name] = result
            if not result.get("real", False):
                stage_result["passed"] = False
        
        return stage_result
    
    def run(self):
        """Run complete validation."""
        logger.info("=" * 70)
        logger.info("RTL-Gen AI Pipeline Output Validation")
        logger.info("=" * 70)
        
        # Find latest test
        test_dir = self.find_latest_test()
        if not test_dir:
            logger.error("No integration test results found")
            return False
        
        self.report["test_run"] = test_dir.name
        logger.info(f"Validating: {test_dir.name}")
        logger.info("")
        
        # Define stages to validate
        stages = [
            (2, "synthesis", [
                {"name": "adder_8bit_synth.v", "validator": "netlist"},
            ]),
            (3, "floorplan", [
                {"name": "floorplan.def", "validator": "def"},
            ]),
            (4, "placement", [
                {"name": "placed.def", "validator": "def"},
            ]),
            (5, "cts", [
                {"name": "cts.def", "validator": "def"},
            ]),
            (6, "global_route", [
                {"name": "route_guides.txt", "validator": "text"},
            ]),
            (7, "detail_route", [
                {"name": "routed.def", "validator": "def"},
            ]),
            (8, "gds", [
                {"name": "adder_8bit.gds", "validator": "binary"},
            ]),
        ]
        
        # Validate each stage
        all_passed = True
        for stage_num, stage_name, files in stages:
            logger.info(f"Stage {stage_num}: {stage_name}")
            result = self.validate_stage(test_dir, stage_num, stage_name, files)
            
            self.report["stages"][stage_name] = result
            self.report["summary"]["total_stages_checked"] += 1
            
            if result["passed"]:
                logger.info(f"  ✅ REAL OUTPUT")
                self.report["summary"]["real_outputs"] += 1
                
                # Log details
                for file_name, file_result in result["files"].items():
                    if file_result.get("real"):
                        size = file_result.get("validation", {}).get("file_size_bytes", 0)
                        logger.info(f"    ✓ {file_name} ({size} bytes)")
                        
                        # Log specific validations
                        if "sky130_cells_count" in file_result.get("validation", {}):
                            count = file_result["validation"]["sky130_cells_count"]
                            logger.info(f"      Sky130 cells: {count}")
            else:
                logger.info(f"  ❌ FAKE/MISSING OUTPUT")
                all_passed = False
                self.report["summary"]["fake_outputs"] += 1
                
                # Log issues
                for file_name, file_result in result["files"].items():
                    if file_result.get("issues"):
                        for issue in file_result["issues"]:
                            logger.info(f"    ⚠️  {file_name}: {issue}")
            
            logger.info("")
        
        # Summary
        logger.info("=" * 70)
        logger.info("VALIDATION SUMMARY")
        logger.info("=" * 70)
        summary = self.report["summary"]
        logger.info(f"Stages checked: {summary['total_stages_checked']}")
        logger.info(f"Real outputs: {summary['real_outputs']}")
        logger.info(f"Fake/missing outputs: {summary['fake_outputs']}")
        logger.info(f"Success rate: {summary['real_outputs']}/{summary['total_stages_checked']} stages")
        
        # Save report
        report_path = VALIDATION_DIR / "pipeline_validation_report.json"
        with open(report_path, "w") as f:
            json.dump(self.report, f, indent=2)
        logger.info(f"\nReport saved to: {report_path}")
        
        return all_passed


if __name__ == "__main__":
    validator = OutputValidator()
    success = validator.run()
    sys.exit(0 if success else 1)
