// Gate-level netlist for adder_8bit
// Generated by RTL-Gen AI Synthesis (Mock Mode)
// Date: 2026-03-26 18:21:09
// Technology: asic

module adder_8bit_netlist (
    input  wire in_0,
    input  wire in_1,
    output wire out_0,
    output wire out_1
);

    // Internal signals

    // Gate-level implementation
    and gate_0 (.a(in_0), .b(in_1), .y(n0));
    and gate_1 (.a(in_1), .b(in_0), .y(n1));
    and gate_2 (.a(in_0), .b(in_1), .y(n2));
    and gate_3 (.a(in_1), .b(in_0), .y(n3));
    or gate_4 (.a(in_0), .b(in_1), .y(n4));
    or gate_5 (.a(in_1), .b(in_0), .y(n5));
    or gate_6 (.a(in_0), .b(in_1), .y(n6));
    or gate_7 (.a(in_1), .b(in_0), .y(n7));
    nand gate_8 (.a(in_0), .b(in_1), .y(n8));
    nand gate_9 (.a(in_1), .b(in_0), .y(n9));
    nand gate_10 (.a(in_0), .b(in_1), .y(n10));
    nand gate_11 (.a(in_1), .b(in_0), .y(n11));
    nor gate_12 (.a(in_0), .b(in_1), .y(n12));
    nor gate_13 (.a(in_1), .b(in_0), .y(n13));
    nor gate_14 (.a(in_0), .b(in_1), .y(n14));
    nor gate_15 (.a(in_1), .b(in_0), .y(n15));
    dff dff_16 (.clk(clk), .d(n16), .q(n17));
    inv gate_17 (.a(in_1), .b(in_0), .y(n17));
    buf gate_18 (.a(in_0), .b(in_1), .y(n18));

    // Output assignments
    assign out_0 = n0;
    assign out_1 = n1;

endmodule
