/* Generated by Yosys 0.38 (git sha1 543faed9c8c, clang++ 17.0.6 -fPIC -Os) */

module counter_4bit(clk, rst, en, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  input clk;
  wire clk;
  output [3:0] count;
  wire [3:0] count;
  input en;
  wire en;
  input rst;
  wire rst;
  sky130_fd_sc_hd__and3_1 _10_ (
    .A(en),
    .B(count[1]),
    .C(count[0]),
    .X(_04_)
  );
  sky130_fd_sc_hd__and4_1 _11_ (
    .A(count[2]),
    .B(en),
    .C(count[1]),
    .D(count[0]),
    .X(_05_)
  );
  sky130_fd_sc_hd__xnor2_1 _12_ (
    .A(count[3]),
    .B(_05_),
    .Y(_06_)
  );
  sky130_fd_sc_hd__nor2_1 _13_ (
    .A(rst),
    .B(_06_),
    .Y(_00_)
  );
  sky130_fd_sc_hd__a21oi_1 _14_ (
    .A1(en),
    .A2(count[0]),
    .B1(rst),
    .Y(_07_)
  );
  sky130_fd_sc_hd__o21a_1 _15_ (
    .A1(en),
    .A2(count[0]),
    .B1(_07_),
    .X(_01_)
  );
  sky130_fd_sc_hd__a21oi_1 _16_ (
    .A1(en),
    .A2(count[0]),
    .B1(count[1]),
    .Y(_08_)
  );
  sky130_fd_sc_hd__nor3_1 _17_ (
    .A(rst),
    .B(_04_),
    .C(_08_),
    .Y(_02_)
  );
  sky130_fd_sc_hd__nor2_1 _18_ (
    .A(count[2]),
    .B(_04_),
    .Y(_09_)
  );
  sky130_fd_sc_hd__nor3_1 _19_ (
    .A(rst),
    .B(_05_),
    .C(_09_),
    .Y(_03_)
  );
  sky130_fd_sc_hd__dfxtp_1 _20_ (
    .CLK(clk),
    .D(_00_),
    .Q(count[3])
  );
  sky130_fd_sc_hd__dfxtp_1 _21_ (
    .CLK(clk),
    .D(_01_),
    .Q(count[0])
  );
  sky130_fd_sc_hd__dfxtp_1 _22_ (
    .CLK(clk),
    .D(_02_),
    .Q(count[1])
  );
  sky130_fd_sc_hd__dfxtp_1 _23_ (
    .CLK(clk),
    .D(_03_),
    .Q(count[2])
  );
endmodule
